In [5]:
import pandas as pd

game_df = pd.read_csv(r'..\data\games.csv')
game_df.head(3)

,BGGId,Name,Description,YearPublished,GameWeight,AvgRating,BayesAvgRating,StdDev,MinPlayers,MaxPlayers,...,Rank:partygames,Rank:childrensgames,Cat:Thematic,Cat:Strategy,Cat:War,Cat:Family,Cat:CGS,Cat:Abstract,Cat:Party,Cat:Childrens
0,1,Die Macher,die macher game seven sequential political rac...,1986,4.3206,7.61428,7.10363,1.57979,3,5,...,21926,21926,0,1,0,0,0,0,0,0
1,2,Dragonmaster,dragonmaster tricktaking card game base old ga...,1981,1.9630,6.64537,5.78447,1.45440,3,4,...,21926,21926,0,1,0,0,0,0,0,0
2,3,Samurai,samurai set medieval japan player compete gain...,1998,2.4859,7.45601,7.23994,1.18227,2,4,...,21926,21926,0,1,0,0,0,0,0,0

In [2]:
print('데이터 프레임 크기: ', game_df.shape)

데이터 프레임 크기:  (21925, 48)

In [6]:
game_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 21925 entries, 0 to 21924
Data columns (total 48 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   BGGId                21925 non-null  int64
 1   Name                 21925 non-null  str
 2   Description          21924 non-null  str
 3   YearPublished        21925 non-null  int64
 4   GameWeight           21925 non-null  float64
 5   AvgRating            21925 non-null  float64
 6   BayesAvgRating       21925 non-null  float64
 7   StdDev               21925 non-null  float64
 8   MinPlayers           21925 non-null  int64
 9   MaxPlayers           21925 non-null  int64
 10  ComAgeRec            16395 non-null  float64
 11  LanguageEase         16034 non-null  float64
 12  BestPlayers          21925 non-null  int64
 13  GoodPlayers          21925 non-null  str
 14  NumOwned             21925 non-null  int64
 15  NumWant              21925 non-null  int64
 16  NumWish              21925 non-null  int64
 17  NumWeightVotes       21925 non-null  int64
 18  MfgPlaytime          21925 non-null  int64
 19  ComMinPlaytime       21925 non-null  int64
 20  ComMaxPlaytime       21925 non-null  int64
 21  MfgAgeRec            21925 non-null  int64
 22  NumUserRatings       21925 non-null  int64
 23  NumComments          21925 non-null  int64
 24  NumAlternates        21925 non-null  int64
 25  NumExpansions        21925 non-null  int64
 26  NumImplementations   21925 non-null  int64
 27  IsReimplementation   21925 non-null  int64
 28  Family               6663 non-null   str
 29  Kickstarted          21925 non-null  int64
 30  ImagePath            21908 non-null  str
 31  Rank:boardgame       21925 non-null  int64
 32  Rank:strategygames   21925 non-null  int64
 33  Rank:abstracts       21925 non-null  int64
 34  Rank:familygames     21925 non-null  int64
 35  Rank:thematic        21925 non-null  int64
 36  Rank:cgs             21925 non-null  int64
 37  Rank:wargames        21925 non-null  int64
 38  Rank:partygames      21925 non-null  int64
 39  Rank:childrensgames  21925 non-null  int64
 40  Cat:Thematic         21925 non-null  int64
 41  Cat:Strategy         21925 non-null  int64
 42  Cat:War              21925 non-null  int64
 43  Cat:Family           21925 non-null  int64
 44  Cat:CGS              21925 non-null  int64
 45  Cat:Abstract         21925 non-null  int64
 46  Cat:Party            21925 non-null  int64
 47  Cat:Childrens        21925 non-null  int64
dtypes: float64(6), int64(37), str(5)
memory usage: 8.0 MB

In [7]:
game_df.describe()

,BGGId,YearPublished,GameWeight,AvgRating,BayesAvgRating,StdDev,MinPlayers,MaxPlayers,ComAgeRec,LanguageEase,...,Rank:partygames,Rank:childrensgames,Cat:Thematic,Cat:Strategy,Cat:War,Cat:Family,Cat:CGS,Cat:Abstract,Cat:Party,Cat:Childrens
count,21925.000000,21925.000000,21925.000000,21925.000000,21925.000000,21925.000000,21925.000000,21925.000000,16395.000000,16034.000000,...,21925.000000,21925.000000,21925.000000,21925.00000,21925.000000,21925.000000,21925.000000,21925.000000,21925.000000,21925.000000
mean,117652.663216,1985.494914,1.982131,6.424922,5.685673,1.516374,2.007343,5.707868,10.004391,216.461819,...,21295.352201,21062.680274,0.055827,0.10577,0.161003,0.105633,0.013820,0.050855,0.029190,0.040182
std,104628.721777,212.486214,0.848983,0.932477,0.365311,0.285578,0.693093,15.014643,3.269157,236.595136,...,3637.139987,4219.776597,0.229592,0.30755,0.367542,0.307374,0.116745,0.219707,0.168344,0.196391
min,1.000000,-3500.000000,0.000000,1.041330,3.574810,0.196023,0.000000,0.000000,2.000000,1.000000,...,1.000000,1.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,12346.000000,2001.000000,1.333300,5.836960,5.510300,1.320720,2.000000,4.000000,8.000000,24.027778,...,21926.000000,21926.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,105305.000000,2011.000000,1.968800,6.453950,5.546540,1.476880,2.000000,4.000000,10.000000,138.000000,...,21926.000000,21926.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,206169.000000,2017.000000,2.525200,7.052450,5.679890,1.665470,2.000000,6.000000,12.000000,351.000000,...,21926.000000,21926.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,349161.000000,2021.000000,5.000000,9.914290,8.514880,4.277280,10.000000,999.000000,21.000000,1757.000000,...,21926.000000,21926.000000,1.000000,1.00000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [8]:
value_counts = game_df['GoodPlayers'].value_counts()
print(value_counts)

GoodPlayers
[]                                          19946
['2', '3', '4']                               600
['3', '4', '5']                               185
['2']                                         158
['1', '2', '3', '4']                          140
                                            ...
['2', '6']                                      1
['5', '6', '7', '8', '9', '10', '11']           1
['6', '7', '8', '9', '10']                      1
['1', '2', '3', '4', '4+']                      1
['1', '2', '3', '4', '5', '6', '7', '8']        1
Name: count, Length: 78, dtype: int64

In [8]:
game_YearPublished = game_df['YearPublished']
print(type(game_YearPublished))

<class 'pandas.Series'>

In [9]:
game_YearPublished.head()

0    1986
1    1981
2    1998
3    1992
4    1964
Name: YearPublished, dtype: int64

In [9]:
value_counts = game_df['GoodPlayers'].value_counts()
print(type(value_counts))
print(value_counts)

<class 'pandas.Series'>
GoodPlayers
[]                                          19946
['2', '3', '4']                               600
['3', '4', '5']                               185
['2']                                         158
['1', '2', '3', '4']                          140
                                            ...
['2', '6']                                      1
['5', '6', '7', '8', '9', '10', '11']           1
['6', '7', '8', '9', '10']                      1
['1', '2', '3', '4', '4+']                      1
['1', '2', '3', '4', '5', '6', '7', '8']        1
Name: count, Length: 78, dtype: int64